---
- hosts: localhost
  connection: local # runs on local machine
  become: true # sets sudo

  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - tmux
        - vim
