---
- hosts: localhost
  connection: local # runs on local machine
  become: true # sets sudo

  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - tmux
        - vim

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: owen
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/wallpaper.png'"

  - name: set wallpaper position
    become_user: owen
    dconf: 
      key: ".org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  
